#!/usr/bin/env bash
# This script configures Nginx to include a custom X-Served-By header in its HTTP responses.

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Get the server hostname
hostname=$(hostname)

# Configure Nginx to include custom header
echo "add_header X-Served-By \"$hostname\";" | sudo tee -a /etc/nginx/sites-available/default > /dev/null

# Restart Nginx to apply changes
sudo service nginx restart

