#!/usr/bin/env bash

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to include custom header
echo "add_header X-Served-By \$hostname;" | sudo tee -a /etc/nginx/sites-available/default > /dev/null

# Restart Nginx to apply changes
sudo service nginx restart

