#!/usr/bin/env bash

# Update package information
apt-get update

# Install Nginx
apt-get install -y nginx

# Check if Nginx installation was successful
if [ $? -eq 0 ]; then
    echo "Nginx installation successful"
else
    echo "Nginx installation failed. Exiting."
    exit 1
fi

# Set variables
web_root="/etc/nginx/html"
index_file="index.html"
nginx_config="/etc/nginx/sites-available/default"

# Create web root directory
mkdir -p "$web_root"

# Create index file with content
echo "Holberton School" > "$web_root/$index_file"

# Configure Nginx
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        $web_root;
     index       $index_file index.htm;
     location / {
         try_files \$uri \$uri/ =404;
     }
}
" > "$nginx_config"

# Restart Nginx to apply changes
service nginx restart

# Check if Nginx restart was successful
if [ $? -eq 0 ]; then
    echo "Nginx configuration successful"
else
    echo "Nginx configuration failed. Exiting."
    exit 1
fi

echo "Script execution complete."

