#!/usr/bin/env bash
# installs the reverse proxy - Nginx
sudo apt update && sudo apt upgrade -y
sudo apt install nginx -y 

# Remove the default Nginx configuration
sudo rm /etc/nginx/sites-enabled/default

# Create a new Nginx configuration file
sudo tee /etc/nginx/sites-available/holberton <<EOF
server {
    listen 80 default_server;
    server_name _;

    location / {
        root /var/www/html;
        index index.html;
    }
}
EOF

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/holberton /etc/nginx/sites-enabled/

# Reload Nginx to apply changes
sudo service nginx reload

# Create the index.html file
echo "Holberton School" | sudo tee /var/www/html/index.html

